### ISSUE TITLE
router reborn advance packger upgrade crash

### ISSUE THREAD

**Issue by monkeybee11** [MyM-ModpackTeam/GalacticScience#132] opened 2016-06-12 18:18 UTC
not able to find the error report but when u right click with a advance packenger upgrade and click on any of the buttions in the gui u get crashed with "fatal error"

**Comment by Slind14** [comment] 2016-06-12 19:56
If this is a client crash, do you have the crash report for us?

**Comment by monkeybee11** [comment] 2016-06-12 20:10
client yes crashreport me am still looking cant find any :(

it was a "open to lan" server didt matter who clicked with the upgrade to make the crash

**Comment by Slind14** [comment] 2016-06-12 20:15
http://docs.mym.li/en/latest/Knowledge_Base/crashreport.html

**Comment by monkeybee11** [comment] 2016-06-12 20:34
https://gyazo.com/2d9125ed04076a311a1517a15beb5003
there is no crashreport folder like it woud normaly make after a crash

**Comment by Sir-Will** [comment] 2016-06-15 18:25
Duplicate of https://github.com/MyM-ModpackTeam/GalacticScience/issues/7

According to the mod dev it has been fixed: https://bitbucket.org/zyberwax/main/issues/32/upgrade-packager-nullpointerexception

Mod will be updated with the next modpack update.

**Closed** 2016-06-15 18:40 UTC
Labels: duplicate
